version: '3.7'
services:
  postgresql-container:
    image: library/postgres:12-alpine
    ports:
      - '7777:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
